ALTER TABLE susuario.t_disciplinas ADD estadodisc int4 NULL;
COMMENT ON COLUMN susuario.t_disciplinas.estadodisc IS '0:activo 1:inactivo';

INSERT INTO susuario.t_disciplinas (iddisc,nombre,codigo,estadodisc) VALUES 
 (1,'No aplica',NULL,0)
,(2,'General',NULL,0)
,(3,'Procesos',NULL,1)
,(4,'Diseño Civil',NULL,0)
,(5,'Costos y Presupuestos',NULL,0)
,(6,'Estructuras',NULL,0)
,(7,'Mecánica',NULL,0)
,(8,'Tuberías',NULL,0)
,(9,'Electricidad',NULL,0)
,(10,'Instrumentación',NULL,0)
,(11,'Hidrología',NULL,0)
,(12,'Hidráulica',NULL,0)
,(13,'Proyectistas CH',NULL,0)
,(14,'Sistema Integrado de Gestión',NULL,0)
,(15,'Seguridad, Salud y Ambiente',NULL,0)
,(16,'Geoprocesos',NULL,0)
,(17,'Geotecnia',NULL,0)
,(18,'Geología',NULL,0)
,(19,'Geofísica',NULL,0)
,(20,'Geomecánica',NULL,0)
,(21,'Gerencia de Proyectos',NULL,0)
,(22,'Planeamiento y Control de Proyectos',NULL,0)
,(23,'Control Documentario',NULL,0)
,(24,'QA Planos y Mapas',NULL,0)
,(26,'Ambiental',NULL,0)
,(36,'Construcción',NULL,0)
,(40,'Gerencia Técnica',NULL,0)
,(41,'Ingenieria',NULL,1)
,(42,'Electromecánica',NULL,1)
,(43,'Laboratorio',NULL,1)
;
